name: Periodic HealthCheck Pipeline # Run at the end of everyday

on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  check_url:
    steps:
      - name: Check the deployed URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://pokedex-flame-two.vercel.app/
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s
          retry-all: false
